### PR TITLE
fix: use transactional client

### LINKED ISSUE #18: Errors during Store insert subset of document data
When an error occurs during `Store()` execution, the data that has been inserted up to that point is not cleaned up, leaving broken references and orphaned data.

Use database transactions (ent `tx` client) to ensure that if an error occurs, the transaction is rolled back to the previous state.

### PR DESCRIPTION
**Pull request by jhoward-lm**
This PR implements the use of ent's transactional client.

If a database error occurs, all changes are rolled back to the previous state at the beginning of the transaction to prevent storing a partial Document with broken references, unknown foreign keys, or orphaned data.

Fixes #18

### CODE REVIEW

File: backends/ent/store.go [hunk 1]
```diff
@@ -441,3 +467,11 @@ func (backend *Backend) newNodeCreate(n *sbom.Node) *ent.NodeCreate {
 
 	return newNode
 }
+
+func rollback(tx *ent.Tx, err error) error {
+	if rollbackErr := tx.Rollback(); rollbackErr != nil {
+		err = fmt.Errorf("rolling back transaction: %w", rollbackErr)
```
Comment (cpanato) [inline backends/ent/store.go:473]: you can return here

```suggestion
		return fmt.Errorf("rolling back transaction: %w", rollbackErr)
```

**Review by cpanato — APPROVED** [review]
non blocking comment

thanks!

File: backends/ent/store.go (hunk 1 above)
Comment (jhoward-lm) [reply backends/ent/store.go]: @cpanato I applied your suggestion but it dismissed your review. Mind re-approving?

**Review by cpanato — APPROVED** [review]
thanks
